# Generated by Django 5.2 on 2025-07-08 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogos', '0005_escolaridad_ocupacion_parentesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Humor', models.IntegerField(blank=True, null=True)),
                ('Culpa', models.IntegerField(blank=True, null=True)),
                ('Suicidio', models.IntegerField(blank=True, null=True)),
                ('IPrecoz', models.IntegerField(blank=True, null=True)),
                ('IIntermedio', models.IntegerField(blank=True, null=True)),
                ('ITardio', models.IntegerField(blank=True, null=True)),
                ('Trabajo', models.IntegerField(blank=True, null=True)),
                ('Inhibicion', models.IntegerField(blank=True, null=True)),
                ('Agitacion', models.IntegerField(blank=True, null=True)),
                ('APsiquica', models.IntegerField(blank=True, null=True)),
                ('ASomatica', models.IntegerField(blank=True, null=True)),
                ('SGastrointestinales', models.IntegerField(blank=True, null=True)),
                ('SGenerales', models.IntegerField(blank=True, null=True)),
                ('SGenitales', models.IntegerField(blank=True, null=True)),
                ('Hipocondria', models.IntegerField(blank=True, null=True)),
                ('Peso', models.IntegerField(blank=True, null=True)),
                ('Introspeccion', models.IntegerField(blank=True, null=True)),
                ('AnimoAnsioso', models.IntegerField(blank=True, null=True)),
                ('Tension', models.IntegerField(blank=True, null=True)),
                ('Temores', models.IntegerField(blank=True, null=True)),
                ('Insomnio', models.IntegerField(blank=True, null=True)),
                ('Intelectual', models.IntegerField(blank=True, null=True)),
                ('AnimoDeprimido', models.IntegerField(blank=True, null=True)),
                ('SomaticosMusculares', models.IntegerField(blank=True, null=True)),
                ('SomaticosSensoriales', models.IntegerField(blank=True, null=True)),
                ('Cardiovasculares', models.IntegerField(blank=True, null=True)),
                ('Respiratorios', models.IntegerField(blank=True, null=True)),
                ('Gastrointestinales', models.IntegerField(blank=True, null=True)),
                ('Genitourinarios', models.IntegerField(blank=True, null=True)),
                ('Autonomos', models.IntegerField(blank=True, null=True)),
                ('Clase', models.CharField(blank=True, max_length=150, null=True)),
                ('Edad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edades', to='Catalogos.edades')),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='Catalogos.generos')),
            ],
            options={
                'db_table': 'entrenamiento',
            },
        ),
    ]
