# Generated by Django 5.2.8 on 2025-12-01 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entrenamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='paciente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre': 'paciente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
