# Generated by Django 5.2 on 2025-04-28 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='descripcion')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cat_categoria',
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='descripcion')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cat_generos',
            },
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='descripcion')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cat_opciones',
            },
        ),
        migrations.CreateModel(
            name='SepoMex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d_codigo', models.CharField(max_length=8)),
                ('d_asenta', models.CharField(max_length=255)),
                ('d_tipo_asenta', models.CharField(max_length=100)),
                ('D_mnpio', models.CharField(max_length=255)),
                ('d_estado', models.CharField(max_length=100)),
                ('d_ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('d_CP', models.CharField(blank=True, max_length=8, null=True)),
                ('c_estado', models.IntegerField(blank=True, null=True)),
                ('c_oficina', models.IntegerField(blank=True, null=True)),
                ('c_CP', models.IntegerField(blank=True, null=True)),
                ('c_tipo_asenta', models.IntegerField(blank=True, null=True)),
                ('c_mnpio', models.IntegerField(blank=True, null=True)),
                ('id_asenta_cpcons', models.IntegerField(blank=True, null=True)),
                ('d_zona', models.CharField(blank=True, max_length=100, null=True)),
                ('c_cve_ciudad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_sepomex',
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='descripcion')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cateogria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Catalogos.categorias')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='Catalogos.opciones')),
            ],
            options={
                'db_table': 'cat_preguntas',
            },
        ),
    ]
