# Generated by Django 5.2 on 2025-04-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='opcion',
        ),
    ]
