# Generated by Django 5.2 on 2025-05-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0003_edades'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='pregunta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='pregunta'),
        ),
    ]
